dist: trusty
sudo: false
language: go
go:
  - 1.11.4
os:
  - linux
  - osx

before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_76567b581e11_key -iv $encrypted_76567b581e11_iv -in gogetcookie.sh.enc -out scripts/gogetcookie.sh -d;
  fi

env:
- GO111MODULE=on

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933#issuecomment-199429151
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then bash scripts/gogetcookie.sh ; fi
- go get ./...
- go get github.com/mitchellh/gox
- go vet
- gox -os "freebsd darwin linux windows" -arch "386 amd64"

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: J2tdeoge01q3exGzEGD0e0kC1NBivOA4EBOOgBIfZ2gpxPkfCULMDIUsfecvD5HMo/HR15AaYAqFmiugdc/Bhu7qNcP2PKQR8UY3SolEdSSWorREPtWwhtfpVNyquMutGGtEgIjaYGbT+n/vt8ht06gbwpRjc0Ujpd0D636w4x2hswnx/68sJTuVJ21fPmZphuD00EqCLewAhHw7PYDqhf5IeNo4sirCrq/xYJ6OYG9ew/7g/gMJGtv/dIt5SRnOaUh7t6yGn4mGHbh292yfnCU+RH+hsyaTE0ZLkGF/AO7bFTxNZ3hF4ozA+YGJXgw4p5iudHsQHdx1Kn/Cc35BSFGMLehkXhR8TRhri4Iyha0IZupGpL3qbet27sXMiM8/mPFbMXdvSdjHfhy2FC6hIQcyQ2nLC110Ss2jDr6kgsGQkLHoYOOZTlh9TPQLiDidCPai5x6oUK/kkd0nc6zMUV2ODLRr7oNH0c+odL9Uo+gaYWAftJ80T8ugDV8p8oRAwVOsfSM+ZNjNrGjkM13RHkvjV8ndjokSXus+kFC/cqSSi+nENOjo6Sv33uKeHIRmlP0t24G/OoXpfD1MNd4wiECnFJ5Kcot1Fofd9lGcph6Igdc2kjv0l6Rx/HdnbnOcPANX5aumHnTLcMe/62Uy3Cdk/C9NanVuFADm4LP8VAw=
  file: terraform-provider-virtualbox*
  file_glob: true
  skip_cleanup: true

  on:
    repo: terra-farm/terraform-provider-virtualbox
    tags: true
