[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  branch = "master"
  name = "github.com/terra-farm/go-virtualbox"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
